import { 
  Heart, 
  Dumbbell, 
  Flame, 
  Target, 
  Users, 
  Crown,
  Sparkles,
  Smartphone,
  Shield,
  BarChart3
} from "lucide-react";
import { TrainerData, ProgramData, FeatureCard } from "@/types/home";

export const TRAINERS_DATA: TrainerData[] = [
  {
    name: "Анна Петрова",
    specialty: "Йога и стретчинг",
    rating: "4.9",
    experience: "5+ лет опыта",
    price: "от 2000₽/час",
    icon: Heart,
    gradient: "from-pink-400 to-purple-600",
    hoverGradient: "hover:from-pink-600 hover:to-purple-700",
    textColor: "text-pink-100",
    iconColor: "text-purple-600",
    badgeColor: "bg-pink-100 text-pink-800",
    description: "Сертифицированный инструктор йоги. Поможет обрести гармонию тела и духа.",
    badges: ["Йога", "Пилатес", "Стретчинг"],
    link: "/trainers/anna-petrova",
    bookingLink: "/book-trainer/anna-petrova",
  },
  {
    name: "Михаил Волков",
    specialty: "Силовые тренировки",
    rating: "4.8",
    experience: "8+ лет опыта",
    price: "от 2500₽/час",
    icon: Dumbbell,
    gradient: "from-blue-500 to-indigo-700",
    hoverGradient: "hover:from-blue-600 hover:to-indigo-800",
    textColor: "text-blue-100",
    iconColor: "text-blue-600",
    badgeColor: "bg-blue-100 text-blue-800",
    description: "Мастер спорта по пауэрлифтингу. Поможет набрать мышечную массу и силу.",
    badges: ["Силовые", "Кроссфит", "Пауэрлифтинг"],
    link: "/trainers/mikhail-volkov",
    bookingLink: "/book-trainer/mikhail-volkov",
  },
  {
    name: "Елена Смирнова",
    specialty: "Кардио и похудение",
    rating: "5.0",
    experience: "6+ лет опыта",
    price: "от 2200₽/час",
    icon: Flame,
    gradient: "from-green-400 to-emerald-600",
    hoverGradient: "hover:from-green-600 hover:to-emerald-700",
    textColor: "text-green-100",
    iconColor: "text-green-600",
    badgeColor: "bg-green-100 text-green-800",
    description: "Специалист по жиросжиганию. Поможет достичь идеальной формы.",
    badges: ["Кардио", "HIIT", "Похудение"],
    link: "/trainers/elena-smirnova",
    bookingLink: "/book-trainer/elena-smirnova",
  },
  {
    name: "Дмитрий Козлов",
    specialty: "Функциональный тренинг",
    rating: "4.7",
    experience: "7+ лет опыта",
    price: "от 2300₽/час",
    icon: Target,
    gradient: "from-orange-400 to-red-600",
    hoverGradient: "hover:from-orange-600 hover:to-red-700",
    textColor: "text-orange-100",
    iconColor: "text-orange-600",
    badgeColor: "bg-orange-100 text-orange-800",
    description: "Эксперт функционального тренинга. Улучшит координацию и выносливость.",
    badges: ["TRX", "Функциональный", "Реабилитация"],
    link: "/trainers/dmitriy-kozlov",
    bookingLink: "/book-trainer/dmitriy-kozlov",
  },
  {
    name: "Ольга Иванова",
    specialty: "Групповые программы",
    rating: "4.9",
    experience: "4+ года опыта",
    price: "от 1800₽/час",
    icon: Users,
    gradient: "from-teal-400 to-cyan-600",
    hoverGradient: "hover:from-teal-600 hover:to-cyan-700",
    textColor: "text-teal-100",
    iconColor: "text-teal-600",
    badgeColor: "bg-teal-100 text-teal-800",
    description: "Энергичный тренер групповых программ. Сделает тренировки веселыми!",
    badges: ["Аэробика", "Зумба", "Степ"],
    link: "/trainers/olga-ivanova",
    bookingLink: "/book-trainer/olga-ivanova",
  },
  {
    name: "Александр Петров",
    specialty: "Персональный тренинг",
    rating: "5.0",
    experience: "10+ лет опыта",
    price: "от 5000₽/час",
    icon: Crown,
    gradient: "from-violet-500 to-purple-700",
    hoverGradient: "hover:from-violet-600 hover:to-purple-800",
    textColor: "text-violet-100",
    iconColor: "text-violet-600",
    badgeColor: "bg-violet-100 text-violet-800",
    description: "Элитный персональный тренер. Работает с VIP-клиентами.",
    badges: ["VIP", "Элитный", "Премиум"],
    link: "/trainers/aleksandr-petrov",
    bookingLink: "/book-trainer/aleksandr-petrov",
  },
];

export const PROGRAMS_DATA: ProgramData[] = [
  {
    title: "Йога и релакс",
    description: "Гармония тела и духа через древние практики йоги и медитации",
    duration: "60-90 мин",
    icon: Heart,
    bgGradient: "bg-gradient-to-br from-pink-50 to-rose-100",
    borderColor: "border-pink-200",
    iconGradient: "from-pink-400 to-rose-500",
    buttonGradient: "from-pink-500 to-rose-600",
    buttonHover: "hover:from-pink-600 hover:to-rose-700",
    link: "/programs/yoga",
  },
  {
    title: "Силовой тренинг",
    description: "Наращивание мышечной массы и увеличение силовых показателей",
    duration: "45-60 мин",
    icon: Dumbbell,
    bgGradient: "bg-gradient-to-br from-blue-50 to-indigo-100",
    borderColor: "border-blue-200",
    iconGradient: "from-blue-500 to-indigo-600",
    buttonGradient: "from-blue-500 to-indigo-600",
    buttonHover: "hover:from-blue-600 hover:to-indigo-700",
    link: "/programs/strength",
  },
  {
    title: "Кардио и жиросжигание",
    description: "Интенсивные кардио-тренировки для быстрого похудения",
    duration: "30-45 мин",
    icon: Flame,
    bgGradient: "bg-gradient-to-br from-green-50 to-emerald-100",
    borderColor: "border-green-200",
    iconGradient: "from-green-500 to-emerald-600",
    buttonGradient: "from-green-500 to-emerald-600",
    buttonHover: "hover:from-green-600 hover:to-emerald-700",
    link: "/programs/cardio",
  },
  {
    title: "Функциональный тренинг",
    description: "Тренировка движений для повседневной активности и спорта",
    duration: "50-70 мин",
    icon: Target,
    bgGradient: "bg-gradient-to-br from-orange-50 to-red-100",
    borderColor: "border-orange-200",
    iconGradient: "from-orange-500 to-red-600",
    buttonGradient: "from-orange-500 to-red-600",
    buttonHover: "hover:from-orange-600 hover:to-red-700",
    link: "/programs/functional",
  },
];

export const NEW_FEATURES: FeatureCard[] = [
  {
    title: "AI Аналитика",
    description: "Умные рекомендации и прогнозы на основе данных",
    icon: Sparkles,
    gradient: "from-purple-500 to-pink-600",
    borderColor: "border-purple-200",
  },
  {
    title: "Мобильное приложение",
    description: "Полный функционал в кармане участника",
    icon: Smartphone,
    gradient: "from-blue-500 to-cyan-600",
    borderColor: "border-blue-200",
  },
  {
    title: "Биометрия",
    description: "Безопасный вход по отпечатку пальца",
    icon: Shield,
    gradient: "from-green-500 to-emerald-600",
    borderColor: "border-green-200",
  },
  {
    title: "Умная аналитика",
    description: "Детальная статистика и отчеты в реальном времени",
    icon: BarChart3,
    gradient: "from-orange-500 to-red-600",
    borderColor: "border-orange-200",
  },
];
